from rsf.proj import *
  
  
  
  
###########################################################################################
def result (data,other):
    Result (data,
             '''
             grey title=%s label1='Time' unit1='s' label2='Trace' unit2=''
             color=g screenratio=1.5 wanttitle=n pclip=99 bar=y scalebar=y
             %s 
             '''%(data,other))
def plot (data,other):
    Plot (data,
             '''
             grey title=%s label1='Time' unit1='s' label2='Trace' unit2=''
             color=g screenratio=1.5 wanttitle=n clip=3 bar=y scalebar=n
             %s 
             '''%(data,other))
def result3 (data, other):
     Result (data,
            '''
            byte clip=0.1 bar=bar.rsf %s| grey3 frame1=150 frame2=30 frame3=15
            title='' label1='Time' unit1='s' label2='Inline' unit2='' label3='Crossline' unit3='' labelsz=6
            flat=n wantaxis=y wanttitle=n color=g point1=0.85 point2=0.8 screenratio=1.3 crowd1=0.65 crowd2=0.6
            '''%(other))
def result3s (data, other):
     Result (data,
            '''
            byte clip=6 bar=bar.rsf %s| grey3 frame1=150 frame2=30 frame3=15
            title='' label1='Time' unit1='s' label2='Inline' unit2='' label3='Crossline' unit3='' labelsz=6
            flat=n wantaxis=y scalebar=y crowd1=0.65 crowd2=0.6 wanttitle=n color=i point1=0.85 point2=0.8 screenratio=1.3
            '''%(other))
def result3c (data, other):
     Result (data,
            '''
            byte clip=0.1 bar=bar.rsf %s| grey3 frame1=20 frame2=30 frame3=2
            title='' label1='Z' unit1='' label2='X' unit2='' label3='Y' unit3=''
            flat=n wantaxis=y wanttitle=n color=g point1=0.85 point2=0.8 crowd1=0.65 crowd2=0.6 screenratio=1.2
            '''%(other))
def plot3 (data, other):
     Plot (data,
            '''
            byte clip=3e+6 bar=bar.rsf %s| grey3 frame1=150 frame2=50 frame3=15
            title='' label1='Time' unit1='s' label2='X' unit2='' label3='Y' unit3=''
            flat=n wantaxis=y wanttitle=n color=g point1=0.85 point2=0.64 screenratio=1.5 o1num=0 d1num=2 n1tic=3 
            '''%(other))
def wig (data, other):
    Result (data,
            '''
            wiggle title=%s transp=y yreverse=y label1='Time' unit1='s' label2='Trace' unit2=''
            screenratio=1
            %s
            '''%(data, other))
def graph (data, other):
    Result (data,
            '''
            graph title=%s label1='Frequency' unit1='Hz' label2='Amplitude' unit2='' screenratio=0.5
            %s
            '''%(data, other))
###########################################################################################



Flow ('sim',  './sim.dat',  'bin2rsf n1=500 n2=2600 | put n1=500 n2=130 n3=20 o1=0 o2=0 o3=0 ')
Flow ('dip',  'sim', 'dip rect1=3 rect2=3 rect3=3 n4=0 order=3')
Flow ('dip.dat', 'dip', 'rsf2bin')


## large-dip difference in ct-domain
Flow ('cof-lar',      './cof-lar.dat', 'bin2rsf n1=4 n2=5628 | put n1=4 n2=67 n3=84 d1=1 d2=1 d3=1 | transp plane=13')
Flow ('cof-all',      './cof-all.dat', 'bin2rsf n1=4 n2=5628 | put n1=4 n2=67 n3=84 d1=1 d2=1 d3=1 | transp plane=13')

## large-dip difference in xt-domain
Flow ('data-lar-xt',  './data-lar-xt.dat', 'bin2rsf n1=500 n2=2600 | put n1=500 n2=130 n3=20 o1=0 o2=0 o3=0')
Flow ('data-lar-ct',  './data-lar-ct.dat', 'bin2rsf n1=500 n2=2600 | put n1=500 n2=130 n3=20 o1=0 o2=0 o3=0')
Flow ('error',        'data-lar-xt data-lar-ct', 'add scale=1,-1 ${SOURCES[1]}')


result3  ('sim', '')
result3s ('dip', 'minval=-6 maxval=1')
result3c ('cof-all', 'clip=0.01')
result3c ('cof-lar', 'clip=0.01')
result3  ('data-lar-xt', '')
result3  ('data-lar-ct', '')
result3  ('error', '')







End ()
