from rsf.proj import *
  
  
  
  
###########################################################################################
def result (data,other):
    Result (data,
             '''
             grey title=%s label1='Time' unit1='s' label2='Trace' unit2=''
             color=g screenratio=1.5 wanttitle=n pclip=99 bar=y scalebar=n
             %s 
             '''%(data,other))
def results (data,other):
    Result (data,
             '''
             grey title=%s label1='Time' unit1='s' label2='Trace' unit2=''
             color=j screenratio=1.5 wanttitle=n pclip=99 bar=y scalebar=n
             %s 
             '''%(data,other))
def plot (data,other):
    Plot (data,
             '''
             grey title=%s label1='Time' unit1='s' label2='Trace' unit2=''
             color=g screenratio=1.5 wanttitle=n clip=3 bar=y scalebar=n
             %s 
             '''%(data,other))
def result3 (data, other):
     Result (data,
            '''
            byte clip=40 bar=bar.rsf %s| grey3 frame1=150 frame2=60 frame3=50
            title='' label1='Time' unit1='s' label2='Inline' unit2='' label3='Crossline' unit3=''
            flat=n wantaxis=y wanttitle=n color=g point1=0.8 point2=0.65 screenratio=1
            '''%(other))
def plot3 (data, other):
     Plot (data,
            '''
            byte clip=3e+6 bar=bar.rsf %s| grey3 frame1=150 frame2=50 frame3=15
            title='' label1='Time' unit1='s' label2='X' unit2='' label3='Y' unit3=''
            flat=n wantaxis=y wanttitle=n color=g point1=0.85 point2=0.64 screenratio=1.5 o1num=0 d1num=2 n1tic=3 
            '''%(other))
def wig (data, other):
    Result (data,
            '''
            wiggle title=%s transp=y yreverse=y label1='Time' unit1='s' label2='Trace' unit2=''
            screenratio=1
            %s
            '''%(data, other))
def graph (data, other):
    Result (data,
            '''
            graph title=%s label1='Frequency' unit1='Hz' label2='Amplitude' unit2='' screenratio=0.5
            %s
            '''%(data, other))

def result3s(data1,other):
	Result(data1,
       '''
       byte clip=0.6 bar=bar.rsf|put d1=0.004 d2=1 d3=1|
       grey3 flat=n frame1=150 frame2=60 frame3=50 
       point1=0.8 point2=0.65 label2=Inline label3=Crossline label1="Time" unit1=s title= color=j
       screenratio=1 scalebar=y minval=0 maxval=0.25 %s'''%other) 

def result3d(data1,other):
	Result(data1,
       '''
       byte gainpanal=e clip=2 bar=bar.rsf|put d1=0.004 d2=1 d3=1|
       grey3 flat=n frame1=150 frame2=60 frame3=50 
       point1=0.8 point2=0.65 label2=Inline label3=Crossline label1="Time" unit1=s title= color=j
       screenratio=1 scalebar=y barlabel="Inline Slpoe" %s'''%other) 

def result3d1(data1,other):
	Result(data1,
       '''
       byte gainpanal=e clip=0.001 bar=bar.rsf|put d1=0.004 d2=1 d3=1|
       grey3 flat=n frame1=150 frame2=60 frame3=50 
       point1=0.8 point2=0.65 label2=Inline label3=Crossline label1="Time" unit1=s title= color=g
       screenratio=1 scalebar=n barlabel="Inline Slpoe" %s'''%other) 

###########################################################################################


Flow ('noise-1',      './noise.dat', 'bin2rsf n1=250 n2=15096 | put n1=250 n2=111 n3=136')
Flow ('ndip-1',       'noise-1',     'dip rect1=7 rect2=7 rect3=7 order=5 n4=0 verb=n')
Flow ('ndip-th-1',    'ndip-1',      'thr mod=hard thr=1 | math output="abs(input)"')
Flow ('ndip.dat',     'ndip-1',      'rsf2bin')
result3 ('noise-1', '')

# result3d  ('ndip-1','')
# result3d1 ('ndip-th-1', 'clip=1')


Flow ('th_global-1', './th_global.dat', 'bin2rsf n1=250 n2=15096 | put n1=250 n2=111 n3=136')
Flow ('th_multi-1',  './th_multi.dat',  'bin2rsf n1=250 n2=15096 | put n1=250 n2=111 n3=136')
Flow ('th_mdip-1',   './th_mdip.dat',   'bin2rsf n1=250 n2=15096 | put n1=250 n2=111 n3=136')
Flow ('diff0-1',     'noise-1 th_global-1', 'add scale=1,-1 ${SOURCES[1]}')
Flow ('diff1-1',     'noise-1 th_multi-1',  'add scale=1,-1 ${SOURCES[1]}')
Flow ('diff2-1',     'noise-1 th_mdip-1',   'add scale=1,-1 ${SOURCES[1]}')

result3 ('th_global-1', '')
result3 ('th_multi-1',  '')
result3 ('th_mdip-1',   '')
result3 ('diff0-1', '')
result3 ('diff1-1', '')
result3 ('diff2-1', '')



Flow ('simi0-1', 'th_global-1 diff0-1'     ,'similarity rect1=5 rect2=5 rect3=5 verb=n other=${SOURCES[1]}')
Flow ('simi1-1', 'th_multi-1  diff1-1'     ,'similarity rect1=5 rect2=5 rect3=5 verb=n other=${SOURCES[1]}')
Flow ('simi2-1', 'th_mdip-1   diff2-1'     ,'similarity rect1=5 rect2=5 rect3=5 verb=n other=${SOURCES[1]}')

result3s ('simi0-1', '')
result3s ('simi1-1', '')
result3s ('simi2-1', '')


Plot('label0',None,
    '''
    box x0=2.945 y0=3.3005 label="" xt=-0.400000 yt=-0.400000 lab_fat=2 lab_color=7 boxit=1 size=0.350000 pointer=1 x_oval=0.000000 y_oval=0.000000
    ''')
Plot('label1',None,
    '''
    box x0=2.603 y0=5.186 label="" xt=0.400000 yt=0.400000 lab_fat=2 lab_color=7 boxit=1 size=0.350000 pointer=1 x_oval=0.000000 y_oval=0.000000
    ''')
Plot('label2',None,
    '''
    box x0=4.370 y0=8.340 label="" xt=0.400000 yt=0.400000 lab_fat=2 lab_color=7 boxit=1 size=0.350000 pointer=1 x_oval=0.000000 y_oval=0.000000
    ''')
Plot('label3',None,
    '''
    box x0=2.696 y0=4.806 label="" xt=0.400000 yt=0.400000 lab_fat=2 lab_color=7 boxit=1 size=0.350000 pointer=1 x_oval=0.000000 y_oval=0.000000
    ''')

Result ('simi0-m-1',   'Fig/simi0-1.vpl label0 label1 label2', 'Overlay')
Result ('simi1-m-1' ,  'Fig/simi1-1.vpl label0 label1 label2', 'Overlay')
Result ('simi2-m-1'  , 'Fig/simi2-1.vpl label0 label1 label2', 'Overlay')
Result ('diff0-m-1'  , 'Fig/diff0-1.vpl label3', 'Overlay')
Result ('diff1-m-1'  , 'Fig/diff1-1.vpl label3', 'Overlay')
Result ('diff2-m-1'  , 'Fig/diff2-1.vpl label3', 'Overlay')



End ()


